name: Deploy Web

on:
  workflow_dispatch:
    inputs:
      build_run_id:
        description: 'Build Run ID'
        required: true

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./dist
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.inputs.build_run_id }}
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload Artifacts to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
      - name: Deploy GitHub Page
        id: deployment
        uses: actions/deploy-pages@v4